name: Health Check

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 8 * * 1'  # Every Monday at 8 AM UTC

# Simple health check workflow that runs basic validation
jobs:
  health-check:
    name: Quick Health Check
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Quick validation
        run: |
          echo "Running quick health checks..."
          node --version
          pnpm --version
          pnpm list --depth=0
          echo "Health check completed ✅"

      - name: Test core functionality
        run: |
          echo "Testing basic functionality..."
          pnpm exec biome --version
          pnpm exec vitest --version
          pnpm exec next --version
          echo "Core tools are working ✅"